# Generated by Django 5.2.1 on 2025-11-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': False},
        ),
    ]
