# Generated by Django 5.2.1 on 2025-11-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_teacher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('type', models.CharField(choices=[('экзамен', 'Экзамен'), ('зачет', 'Зачёт')], max_length=10, verbose_name='Тип')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('classroom', models.CharField(blank=True, max_length=50, verbose_name='Аудитория')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='Преподаватель')),
                ('passed', models.BooleanField(default=False, verbose_name='Сдан')),
            ],
            options={
                'verbose_name': 'Экзамен/зачёт',
                'verbose_name_plural': 'Экзамены и зачёты',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('subject_type', models.CharField(choices=[('exam', 'Экзамен'), ('test', 'Зачёт')], max_length=10, verbose_name='Тип')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('classroom', models.CharField(blank=True, max_length=50, verbose_name='Аудитория')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='Преподаватель')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['date', 'time'],
            },
        ),
    ]
