# Generated by Django 5.2 on 2025-11-27 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_studentnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='studentnote',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studentnote',
            name='author',
            field=models.ForeignKey(default=1, help_text='Кто создал заметку (для групповых - тоже нужно знать автора)', on_delete=django.db.models.deletion.CASCADE, related_name='authored_notes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentnote',
            name='group_number',
            field=models.CharField(blank=True, help_text='Номер группы, для которой видна заметка, если она групповая', max_length=4),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='is_group_note',
            field=models.BooleanField(default=False, help_text='Отметка, что заметка достунпа всем студентам этой группы'),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='student',
            field=models.ForeignKey(help_text='Владелец заметки (для личных заметок)', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='text',
            field=models.TextField(),
        ),
    ]
